model_args:
  agent_type: "uitars_1.5"
  model_name: "ByteDance-Seed/UI-TARS-1.5-7B"
  max_trajectory_length: 40
  base_url: "http://127.0.0.1:18001/v1"
  observation_type: "screenshot"
  action_space: "pyautogui"
  model_type: "qwen25vl"  # choices: ["qwen25vl", "qwen2vl"]
  infer_mode: "qwen25vl_normal"  # choices: ["qwen25vl_normal", "qwen2vl_user"]
  prompt_style: "qwen25vl_normal"  # choices: ["qwen25vl_normal", "qwen2vl_user", "qwen2vl_user"]
  input_swap: true
  language: "English" #"Chinese"
  max_pixels: 12845056.0  # 16384 * 28 * 28
  min_pixels: 78400.0     # 100 * 28 * 28
  temperature: 1.0
  top_p: 0.9
  top_k: -1
  history_n: 10
  callusr_tolerance: 5
  max_tokens: 500
  stop_token: null
